import '@/configs/setup-console';
import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Inter,
  Roboto,
  Bebas_Neue,
  Kode_Mono,
  Poppins,
  Montserrat,
  Open_Sans,
  Lato,
  Raleway,
  Playfair_Display,
} from 'next/font/google';
import './globals.css';
import { Providers } from '@/providers/providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  weight: '400',
  subsets: ['latin'],
});

const kodeMono = Kode_Mono({
  variable: '--font-kode-mono',
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

const lato = Lato({
  variable: '--font-lato',
  weight: ['400', '700'],
  subsets: ['latin'],
});

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AutoFeather',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bebasNeue.variable} ${geistSans.variable} ${geistMono.variable} ${inter.variable} ${kodeMono.variable} ${roboto.variable} ${poppins.variable} ${montserrat.variable} ${openSans.variable} ${lato.variable} ${raleway.variable} ${playfair.variable} antialiased`}
        style={{ fontFamily: 'var(--active-font, var(--font-roboto))' }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
