export const roleAccessMap: Record<string, string[]> = {
  administrator: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/chicken-breed-library',
  ],
  moderator: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/chicken-breed-library',
  ],
  user: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/chicken-breed-library',
  ],
  researcher: [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/chicken-breed-library',
  ],

  'poultry-operator': [
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/chicken-breed-library',
  ],

  'monitoring-manager': [
    '/admin/users',
    '/admin/roles',
    '/admin/permissions',
    '/admin/audit-logs',
    '/notifications',
    '/dashboard',
    '/profile',
    '/account',
    '/temperature-monitoring',
    '/chicken-breed-library',
  ],
};
