import { DataSource } from 'typeorm';
import { ChickenBreed } from 'src/modules/predict/entities/chicken-breed.entity';
import { BreedPurposeEnum } from 'src/modules/predict/enums/chicken-breed.enum';
import { v7 as uuidv7 } from 'uuid';

export class ChickenBreedSeeder {
  static async run(dataSource: DataSource): Promise<void> {
    const chickenBreedRepository = dataSource.getRepository(ChickenBreed);

    const breeds = [
      {
        id: uuidv7(),
        code: 'RIR001',
        chickenName: 'Rhode Island Red',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'An iconic American breed developed in the late 19th century in Rhode Island and Massachusetts. Created by crossing Red Malay Game, Leghorn, and Asiatic stock. Known for their hardiness, reliability, and dual-purpose capabilities.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 260,
        meatType: 'Good quality table bird',
        plumageColor: 'Deep reddish-brown with black highlights',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Hardy, friendly, active',
        climateTolerance: 'Adaptable to various climates',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'LEG001',
        chickenName: 'White Leghorn',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'Italy',
        description:
          'Originating from Tuscany, Italy, first exported to North America in 1828 from the port city of Livorno. The standard white egg-laying breed used commercially worldwide. Excellent egg production with minimal feed consumption.',
        purpose: BreedPurposeEnum.EGG,
        eggColor: 'White',
        eggPerYear: 300,
        meatType: 'Light meat, not ideal for meat production',
        plumageColor: 'Pure white',
        combType: 'Single comb',
        averageWeight: 5.0,
        temperament: 'Active, independent, nervous, flighty',
        climateTolerance: 'Prefers warmer climates',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'PLY001',
        chickenName: 'Plymouth Rock (Barred Rock)',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'First seen in Massachusetts in the 19th century. Historically the most popular breed in the United States until WWII. Known for distinctive black and white barred plumage and excellent dual-purpose qualities.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Light brown',
        eggPerYear: 250,
        meatType: 'Excellent table quality',
        plumageColor: 'Black and white barred pattern',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Docile, friendly, calm, great with children',
        climateTolerance: 'Versatile, handles various climates',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'AUS001',
        chickenName: 'Black Australorp',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'Australia',
        description:
          'Developed in Australia from Black Orpington stock through careful selection. Holds world records for egg production. Known for their beetle-green sheen on black feathers and exceptional laying ability.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 280,
        meatType: 'Good quality meat production',
        plumageColor: 'Black with beetle-green sheen',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Calm, docile, friendly, easily handled',
        climateTolerance: 'Excellent in both hot and cold climates',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'ORP001',
        chickenName: 'Buff Orpington',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'England',
        description:
          'English breed recognized in 1902, celebrated for its golden plumage and gentle nature. Large, stately birds with a friendly and quiet disposition. Popular as family pets and backyard chickens.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Light pinkish-brown',
        eggPerYear: 180,
        meatType: 'Excellent meat quality, large bird',
        plumageColor: 'Golden buff',
        combType: 'Single comb',
        averageWeight: 8.5,
        temperament: 'Very docile, friendly, quiet, great mothers',
        climateTolerance: 'Excellent in cold climates, thick plumage',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'SUS001',
        chickenName: 'Light Sussex',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'England',
        description:
          'A very old English breed known for its beauty and productivity. One of the most popular dual-purpose breeds. Features distinctive white body with black neck and tail feathers.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Light brown to tinted',
        eggPerYear: 270,
        meatType: 'Excellent table quality',
        plumageColor: 'White body with black neck and tail',
        combType: 'Single comb',
        averageWeight: 7.0,
        temperament: 'Calm, friendly, curious',
        climateTolerance: 'Adaptable to various climates',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'WYA001',
        chickenName: 'Silver Laced Wyandotte',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'American breed developed in the 1870s. Named after the Wyandot people. Dual-purpose breed known for its striking black-laced silvery white feathers and rose comb.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 220,
        meatType: 'Yellow-skinned quality meat',
        plumageColor: 'Silvery white with black lacing',
        combType: 'Rose comb',
        averageWeight: 7.0,
        temperament: 'Friendly, docile, calm',
        climateTolerance: 'Hardy, cold-tolerant',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'JGT001',
        chickenName: 'Jersey Giant',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Developed between 1870-1890 in New Jersey by crossing Black Javas, Dark Brahmas, and Black Langshans. The largest purebred chicken breed. Roosters can reach 13 pounds.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 200,
        meatType: 'Excellent meat production, largest breed',
        plumageColor: 'Usually black, also white varieties',
        combType: 'Single comb',
        averageWeight: 11.5,
        temperament: 'Calm, docile, gentle despite large size',
        climateTolerance: 'Hardy, adaptable',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'BRA001',
        chickenName: 'Light Brahma',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Large, gentle birds ideal for cold climates. Known for their feathered legs and feet, and distinctive white plumage with black accents on neck and tail. Excellent winter layers.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 180,
        meatType: 'Good meat quality, large birds',
        plumageColor: 'White with black neck and tail accents',
        combType: 'Pea comb',
        averageWeight: 9.5,
        temperament: 'Gentle, calm, excellent mothers',
        climateTolerance: 'Excellent in cold, feathered feet',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'DEL001',
        chickenName: 'Delaware',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Developed in Delaware in 1940 by George Ellis, originally known as "Indian Rivers". Created from crosses of Barred Plymouth Rock roosters and New Hampshire hens. Originally intended as a meat bird.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 230,
        meatType: 'Excellent meat production',
        plumageColor: 'White with black barring on neck and tail',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Calm, friendly, docile',
        climateTolerance: 'Hardy, adaptable',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'HAM001',
        chickenName: 'Hamburg',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'Holland',
        description:
          'Ancient breed from Holland. Active and flighty birds that prefer to roost in trees. Known for laying large numbers of eggs over a longer period of their lifetime than most breeds.',
        purpose: BreedPurposeEnum.EGG,
        eggColor: 'White',
        eggPerYear: 220,
        meatType: 'Light meat, small bird',
        plumageColor: 'Various patterns including spangled',
        combType: 'Rose comb',
        averageWeight: 4.5,
        temperament: 'Active, flighty, independent',
        climateTolerance: 'Does well in any climate',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'DOM001',
        chickenName: 'Dominique',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'One of the oldest American breeds. Excellent forager and homestead fowl. Rose comb makes them less susceptible to frostbite. Known for distinctive barred plumage similar to Plymouth Rock.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 250,
        meatType: 'Good breast meat',
        plumageColor: 'Black and white barred',
        combType: 'Rose comb',
        averageWeight: 6.0,
        temperament: 'Active, hardy, good foragers',
        climateTolerance: 'Excellent in any climate',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'NWH001',
        chickenName: 'New Hampshire Red',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Developed from Rhode Island Reds through selective breeding in New Hampshire. Bred for fast growth, early maturity, and rapid feathering. Lighter colored than Rhode Island Reds.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 240,
        meatType: 'Excellent meat production, fast growth',
        plumageColor: 'Light to medium red',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Competitive, vigorous, active',
        climateTolerance: 'Hardy, adaptable',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'JAV001',
        chickenName: 'Black Java',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'Indonesia',
        description:
          'Second oldest chicken breed developed in America (1835), ancestors from the Isle of Java. Known for brilliant beetle-green sheen on black feathers. Excellent for free-ranging homesteads.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Dark brown',
        eggPerYear: 180,
        meatType: 'Good table qualities',
        plumageColor: 'Black with beetle-green sheen',
        combType: 'Single comb',
        averageWeight: 8.0,
        temperament: 'Active, hardy, good foragers',
        climateTolerance: 'Adaptable',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'EEG001',
        chickenName: 'Easter Egger',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Developed in the 1970s from Araucana chickens from Chile. Bred to retain the blue-egg gene. Not a recognized breed but a hybrid type. Known for diverse feather patterns and colorful eggs.',
        purpose: BreedPurposeEnum.EGG,
        eggColor: 'Blue, green, pink, cream (various)',
        eggPerYear: 250,
        meatType: 'Light meat production',
        plumageColor: 'Highly variable, diverse patterns',
        combType: 'Pea comb or single comb',
        averageWeight: 5.0,
        temperament: 'Friendly, curious, individual personalities',
        climateTolerance: 'Hardy, adaptable',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'BCM001',
        chickenName: 'Black Copper Marans',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'France',
        description:
          'French breed from the port town of Marans. Famous for laying the darkest chocolate brown eggs. Highly sought after breed. Cold hardy with slightly sassy personality.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Dark chocolate brown',
        eggPerYear: 200,
        meatType: 'Good quality meat',
        plumageColor: 'Black with copper neck and hackle feathers',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Active, can be sassy, hardy',
        climateTolerance: 'Cold hardy',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'COC001',
        chickenName: 'Buff Cochin',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'China',
        description:
          'Large Asian breed known for their extremely fluffy feathers and feathered legs and feet. Not the best layers but beloved for their gentle, friendly personalities. Excellent mothers and broody hens.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'Brown',
        eggPerYear: 160,
        meatType: 'Heavy meat birds',
        plumageColor: 'Golden buff with heavy feathering',
        combType: 'Single comb',
        averageWeight: 9.0,
        temperament: 'Extremely docile, friendly, gentle, great pets',
        climateTolerance: 'Prefers cold climates',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'SIL001',
        chickenName: 'Silkie',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'China',
        description:
          'Ancient Asian breed with unique fluffy feathers that feel like fur or silk. Black skin and bones. Five toes instead of four. Excellent mothers and extremely gentle, making them popular as pets.',
        purpose: BreedPurposeEnum.EGG,
        eggColor: 'Cream to tinted',
        eggPerYear: 120,
        meatType: 'Traditional Chinese cuisine, black meat',
        plumageColor: 'White, black, blue, buff (silky texture)',
        combType: 'Walnut comb',
        averageWeight: 3.0,
        temperament: 'Extremely gentle, calm, affectionate, great pets',
        climateTolerance: 'Needs shelter, cannot fly',
        broodiness: true,
      },
      {
        id: uuidv7(),
        code: 'COR001',
        chickenName: 'Cornish Cross',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Modern hybrid created by crossing Cornish chickens with White Rocks. Industry standard for meat production. Extremely fast growth reaching 4-6 pounds in 7 weeks, roasting size in 8-12 weeks.',
        purpose: BreedPurposeEnum.MEAT,
        eggColor: 'Brown',
        eggPerYear: 80,
        meatType: 'Excellent meat production, fastest growing',
        plumageColor: 'White',
        combType: 'Pea comb',
        averageWeight: 9.0,
        temperament: 'Calm, docile, less active',
        climateTolerance: 'Needs careful management',
        broodiness: false,
      },
      {
        id: uuidv7(),
        code: 'HOL001',
        chickenName: 'Holland',
        scientificName: 'Gallus gallus domesticus',
        originCountry: 'United States',
        description:
          'Rare American breed on critical conservation status. Developed for dual-purpose production. Top-notch foragers and excellent homestead fowl. Known for docility and good egg production.',
        purpose: BreedPurposeEnum.DUAL,
        eggColor: 'White',
        eggPerYear: 200,
        meatType: 'Good meat quality',
        plumageColor: 'White or barred varieties',
        combType: 'Single comb',
        averageWeight: 7.5,
        temperament: 'Docile, calm, good foragers',
        climateTolerance: 'Does well in hot and cold',
        broodiness: true,
      },
    ];

    for (const breed of breeds) {
      await chickenBreedRepository.save(breed);
    }

    console.log(`Successfully seeded ${breeds.length} chicken breeds`);
  }
}
